### ISSUE TITLE
ordinary `vcat`?

### ISSUE THREAD

**Issue by Moelf** [JuliaArrays/StackViews.jl#4]
something like `Vcat` in https://github.com/JuliaArrays/LazyArrays.jl 
see: https://github.com/JuliaArrays/LazyArrays.jl/blob/cc292528a9fcc72a37ccbc7801590667bed287de/src/lazyconcat.jl#L13

**Comment by johnnychen94** [comment]
Not really possible because `StackView` always creates a new dimension.
